### ISSUE TITLE
LP tool to Submit, Amend, Cancel & View LP orders 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegatools#109]
LPs would benefit from having a tool that allows them to watch their liquidity provision in real time.

**Comment by peterbarrow** [comment]
We already have a tool to allow us to monitor a single party in a single market. However it is missing a few bits of information that might be better viewed in a new tool just for visualising the overall picture for a given market. Such things include:
* Number of liquidity providers
* Total amount committed
* Fee levels
* Target commitment for the market
