### ISSUE TITLE
Liquidity viewer: Can't scroll through all provisions on market

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegatools#138]
The LPs on an order will only display as many as fit in the window, and the only way to view more is to expand the window, but it's not clear that's the case. (Discovered on MacOS) 

https://user-images.githubusercontent.com/62548908/160845601-6391160b-d12c-4289-b611-93d33abdf233.mov

**Comment by gordsport** [comment]
Closing as this has been moved to `done` on the project board
