### ISSUE TITLE
Datanode performance testing

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegatools#187]
As an extension to the core performance testing that is on going we need to test the data-node is performant as the useage of the protocol increases and the number of console instances grows.

Points to consider when testing the data-node performance:

- [ ] How many consoles can be connected to a single data-node before performance degrades
- [ ] What of the performance work already done and networks created can be leveraged for this part of testing

**Comment by peterbarrow** [comment]
The first attempt at this has been completed and is documented here:
https://docs.google.com/document/d/1bm3AMjZkfqlrGHW2IlJQ9DhcYwZMRn9rtZi4ixw4nbQ/edit#heading=h.1uf5xld0pbex
More testing might be required as we make changes to fix perf issues we have found.

**Comment by peterbarrow** [comment]
This is covered by the repo https://github.com/vegaprotocol/consoleLoadTest
