### ISSUE TITLE
Add Github Actions CI

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/vegatools#2]
Actions should be run on pull request to `develop`/`main`/`master`:

- lint yaml files (https://github.com/vegaprotocol/liqbot/blob/develop/.github/workflows/yamllint.yml)
- check Go compilation works on Linux, MacOSX, Windows (https://github.com/vegaprotocol/liqbot/blob/develop/.github/workflows/go.yml) for Go versions `1.16` and `1.15`

**Comment by fkondej** [comment]
Implemented in #4.
