### ISSUE TITLE
rerun perf tests after 0.63.x is tagged

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegatools#250]
Once we have the last of the changes in for the follwoing work:

- [x] MTM calculations
- [x] https://github.com/vegaprotocol/vega/issues/6956
- [x] Tendermint GAS costs/priorities

we need to re run the performance tests and see how the metrics change.

The output from this should be:

- [ ] Information for the validators on config changes (if applic)
- [ ] information to validators on hardware requirements

**Comment by peterbarrow** [comment]
![image](https://user-images.githubusercontent.com/62435083/217798395-df0840c7-3872-4c99-8326-3c4f8e579a69.png)

The MtM changes have resulted in a reduction of events emitted which reduces the load on the datanode. The GAS limit will result in transactions being held back thus reducing the load on the core. Setting the GAS limit very high showed that the order rate matches that of previous versions so no regressions have occurred during these changes. Both of these changes will not impact the recommended hardware and the validators will not need to change anything to benefit from these updates.
